# Generated by Django 3.2.8 on 2021-11-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_tutor_cropped_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cropped_photo',
            field=models.ImageField(blank=True, upload_to='students'),
        ),
    ]
