# Generated by Django 3.2.8 on 2021-12-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_auto_20211206_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='grade',
            new_name='max_grade',
        ),
    ]
