# Generated by Django 3.2.8 on 2021-12-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_auto_20211207_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_docs')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.task')),
            ],
        ),
    ]
