# Generated by Django 3.2.8 on 2021-12-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_auto_20211207_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer_variants', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=100)),
                ('test_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.testpackage')),
            ],
        ),
    ]
