# Generated by Django 3.2.8 on 2021-12-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_testpackage_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='name',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('TEST', 'Test'), ('BASE', 'Basic')], max_length=10),
        ),
    ]
