# Generated by Django 3.2.8 on 2021-12-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_auto_20211213_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpackage',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='test_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.testpackage'),
        ),
    ]
