# Generated by Django 3.2.8 on 2021-12-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_auto_20211213_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms_app.tutor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('TEST', 'New Test Package'), ('XTEST', 'Existing Test'), ('BASE', 'Basic')], max_length=10),
        ),
    ]
